[package]
name = "solri"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
description = "Rust implementation of a minimal self-governed WebAssembly blockchain"
license = "GPL-3.0"
edition = "2018"

[dependencies]
primitive-types = "0.4"
blockchain = "0.8"
blockchain-network-simple = "0.4"
bm-le = { version = "0.8", features = ["with-codec", "with-serde"] }
bm = "0.8"
sha3 = "0.8"
clap = "2.33"
schnorrkel = "0.6"
rand = "0.6"
parity-codec = { version = "4.1", features = ["derive"] }

[workspace]
members = [
	"engine",
	"runtime",
	"metadata",
]
exclude = [
	"utils/wasm-builder",
	"utils/wasm-builder-runner",
]
