[package]
name = "blockchain-network"
version = "0.1.0"
authors = ["Wei Tang <hi@that.world>"]
edition = "2018"

[dependencies]
blockchain = { version = "0.9", path = ".." }
parity-codec = { version = "4.0", features = ["derive"] }
