[package]
name = "blockchain-core"
version = "0.1.2"
authors = ["Wei Tang <hi@that.world>"]
description = "Traits for blockchain"
license = "GPL-3.0"
edition = "2018"

[dependencies]

[features]
default = ["std"]
std = []
