[package]
name = "revdb"
version = "0.1.0"
authors = ["Wei Tang <wei@that.world>"]
description = "Revision database."
edition = "2018"
license = "Apache-2.0"

[dependencies]
rocksdb = "0.14"
codec = { package = "parity-scale-codec", version = "1.3" }

[dev-dependencies]
tempfile = "3.1"
